version: '3'
services:
  api:
    build: ./
    image: car-api
    container_name: api
    ports:
      - "4000:4000"
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
